# Generated by Django 3.2.5 on 2022-10-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='albcounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.CharField(max_length=264, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.CharField(max_length=264, unique=True)),
                ('name', models.CharField(max_length=264)),
                ('filesall', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=264)),
                ('upiid', models.CharField(max_length=264)),
                ('desc', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='short',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=264, unique=True)),
                ('name', models.CharField(max_length=264)),
                ('filesall', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=264)),
                ('upiid', models.CharField(max_length=264)),
                ('desc', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='srtmvcounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=264, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='subdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=264, unique=True)),
                ('sub', models.CharField(max_length=264)),
                ('date', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='userdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=264, unique=True)),
                ('name', models.CharField(max_length=264)),
                ('password', models.CharField(max_length=264)),
            ],
        ),
    ]
